language: node_js

node_js: node

cache:
  directories:
    - node_modules

script:
  - yarn install
  - yarn test
  - bash <(curl -s https://codecov.io/bash)
  - yarn build
  - yarn build-storybook

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        - provider: script
          script: yarn semantic-release

        - provider: pages
          github_token: $GH_TOKEN
          local_dir: storybook-static
          on:
            branch: main
