language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

script:
  - yarn install
  - yarn test
  - yarn build-storybook

deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  on:
    branch: master
