language: node_js

node_js: node

cache:
  directories:
    - node_modules

script:
  - yarn install
  - yarn test
  - bash <(curl -s https://codecov.io/bash)
  - yarn build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  on:
    branch: master
